[package]
name = "mb-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Mikrofon z jednego komputera na drugim po sieci lokalnej"

[lib]
name = "mb_app"
path = "src/lib.rs"

[[bin]]
name = "micbridge"
path = "src/main.rs"

[dependencies]
mb-proto = { path = "../mb-proto" }
mb-audio = { path = "../mb-audio" }
mb-net = { path = "../mb-net" }
mb-engine = { path = "../mb-engine" }
anyhow.workspace = true
clap.workspace = true
ringbuf.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
ctrlc = "3.4"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
