[package]
name = "mb-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
mb-proto = { path = "../mb-proto" }
anyhow.workspace = true
cpal.workspace = true
tracing.workspace = true

# Windows dostaje wirtualne wejście od cudzego sterownika (§4 architektury),
# w Linuksie tworzymy własny węzeł i dlatego zależność jest tylko tutaj.
[target.'cfg(target_os = "linux")'.dependencies]
pipewire = "0.10"
