//! Tabela tekstów. Jeden wiersz to jeden napis we wszystkich językach.
//!
//! Kolumny po kluczu idą zawsze tak samo:
//!
//! ```text
//! Klucz: polski, angielski, niemiecki, hiszpański, francuski, włoski, ukraiński;
//! ```
//!
//! Miejsca do wypełnienia zapisujemy jako `{}` i wypełnia je [`crate::t1`]
//! i pokrewne. Tłumaczenie musi mieć ich tyle samo, co polski oryginał —
//! pilnuje tego test w [`crate`].
//!
//! Polski jest wersją źródłową: gdy tekst się zmienia, zmienia się najpierw
//! tutaj, a reszta kolumn za nim.

use crate::Lang;

macro_rules! katalog {
    ($( $key:ident : $pl:literal, $en:literal, $de:literal, $es:literal, $fr:literal, $it:literal, $uk:literal ; )*) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq)]
        pub enum Key { $($key,)* }

        /// Wszystkie klucze — wyłącznie po to, żeby testy przeszły po
        /// komplecie tabeli. W zwykłym budowaniu nikt tego nie czyta.
        #[cfg(test)]
        pub const ALL: &[Key] = &[ $(Key::$key,)* ];

        pub fn text(key: Key, lang: Lang) -> &'static str {
            match key {
                $(Key::$key => match lang {
                    Lang::Pl => $pl,
                    Lang::En => $en,
                    Lang::De => $de,
                    Lang::Es => $es,
                    Lang::Fr => $fr,
                    Lang::It => $it,
                    Lang::Uk => $uk,
                },)*
            }
        }
    };
}

katalog! {
// --- okno: sekcje i przełączniki -------------------------------------------
Receiving: "Odbieranie", "Receiving", "Empfangen", "Recepción", "Réception", "Ricezione", "Отримування";
ReceivingHint: "mikrofon z drugiej maszyny trafia tutaj", "the other machine’s microphone arrives here", "das Mikrofon der anderen Maschine landet hier", "el micrófono de la otra máquina llega aquí", "le microphone de l’autre machine arrive ici", "il microfono dell’altra macchina arriva qui", "мікрофон іншої машини потрапляє сюди";
Sending: "Wysyłanie", "Sending", "Senden", "Envío", "Envoi", "Invio", "Надсилання";
SendingHint: "mój mikrofon idzie na drugą maszynę", "my microphone goes to the other machine", "mein Mikrofon geht an die andere Maschine", "mi micrófono va a la otra máquina", "mon microphone part vers l’autre machine", "il mio microfono va all’altra macchina", "мій мікрофон іде на іншу машину";
On: "włączone", "on", "ein", "activado", "activé", "attivo", "увімкнено";
Off: "wyłączone", "off", "aus", "desactivado", "désactivé", "inattivo", "вимкнено";
SinkLabel: "Ujście:", "Output:", "Ausgabe:", "Salida:", "Sortie :", "Uscita:", "Вихід:";
BufferLabel: "Bufor:", "Buffer:", "Puffer:", "Búfer:", "Tampon :", "Buffer:", "Буфер:";
AdaptBuffer: "dopasuj do łącza", "adapt to the link", "an die Verbindung anpassen", "adaptar al enlace", "s’adapter à la liaison", "adatta al collegamento", "підлаштовувати під канал";
AdaptBufferHint: "Podnosi poduszkę, gdy pakiety się spóźniają, i opuszcza ją po długiej spokojnej chwili.", "Raises the cushion when packets run late and lowers it after a long quiet spell.", "Erhöht das Polster, wenn Pakete zu spät kommen, und senkt es nach einer langen ruhigen Phase.", "Aumenta el colchón cuando los paquetes llegan tarde y lo reduce tras un largo rato tranquilo.", "Augmente le coussin quand les paquets arrivent en retard et le réduit après une longue période calme.", "Alza il cuscinetto quando i pacchetti arrivano in ritardo e lo abbassa dopo una lunga fase tranquilla.", "Піднімає подушку, коли пакети запізнюються, і опускає її після довгого спокійного часу.";
Announce: "widoczny w sieci", "visible on the network", "im Netzwerk sichtbar", "visible en la red", "visible sur le réseau", "visibile in rete", "видимий у мережі";
AnnounceHint: "Ogłaszanie przez mDNS. Bez tego druga strona podaje adres.", "Announced over mDNS. Without it the other side needs the address.", "Ankündigung über mDNS. Ohne sie muss die Gegenseite die Adresse kennen.", "Anuncio por mDNS. Sin él, el otro extremo necesita la dirección.", "Annonce par mDNS. Sans elle, l’autre côté doit saisir l’adresse.", "Annuncio via mDNS. Senza, l’altro lato deve indicare l’indirizzo.", "Оголошення через mDNS. Без нього інша сторона вводить адресу.";
SettingsAfterStop: "Ustawienia można zmienić po zatrzymaniu.", "Settings can be changed once it is stopped.", "Einstellungen lassen sich nach dem Stoppen ändern.", "Los ajustes se pueden cambiar tras detenerlo.", "Les réglages se modifient après l’arrêt.", "Le impostazioni si cambiano dopo l’arresto.", "Налаштування можна змінити після зупинки.";
MicrophoneLabel: "Mikrofon:", "Microphone:", "Mikrofon:", "Micrófono:", "Microphone :", "Microfono:", "Мікрофон:";
Refresh: "Odśwież", "Refresh", "Aktualisieren", "Actualizar", "Actualiser", "Aggiorna", "Оновити";
RefreshHint: "Przeczytaj listę urządzeń jeszcze raz", "Read the device list again", "Geräteliste erneut einlesen", "Volver a leer la lista de dispositivos", "Relire la liste des périphériques", "Rileggi l’elenco dei dispositivi", "Прочитати список пристроїв ще раз";
ToLabel: "Do:", "To:", "An:", "A:", "Vers :", "A:", "До:";
Search: "Szukaj", "Search", "Suchen", "Buscar", "Rechercher", "Cerca", "Шукати";
OnlyOnNetwork: "jedyny w sieci", "the only one on the network", "der einzige im Netzwerk", "el único en la red", "le seul sur le réseau", "l’unico in rete", "єдиний у мережі";
OnlyOnNetworkHint: "Połącz się z odbiornikiem, jeśli jest dokładnie jeden.", "Connect to the receiver if there is exactly one.", "Mit dem Empfänger verbinden, wenn es genau einen gibt.", "Conectar con el receptor si hay exactamente uno.", "Se connecter au récepteur s’il n’y en a qu’un.", "Collegati al ricevitore se ce n’è esattamente uno.", "З’єднатися з приймачем, якщо він рівно один.";
OtherProtocol: "{}  — inna wersja protokołu", "{}  — different protocol version", "{}  — andere Protokollversion", "{}  — otra versión del protocolo", "{}  — version de protocole différente", "{}  — versione di protocollo diversa", "{}  — інша версія протоколу";
OrIpAddress: "albo adres IP", "or an IP address", "oder eine IP-Adresse", "o una dirección IP", "ou une adresse IP", "oppure un indirizzo IP", "або IP-адреса";
Autostart: "uruchamiaj przy starcie systemu", "start with the system", "mit dem System starten", "iniciar con el sistema", "démarrer avec le système", "avvia con il sistema", "запускати разом із системою";
PairedWith: "Sparowane: {}", "Paired: {}", "Gekoppelt: {}", "Emparejado: {}", "Appairé : {}", "Associato: {}", "Спаровано: {}";
WaitingForPeer: "czekam na drugą stronę", "waiting for the other side", "warte auf die Gegenseite", "esperando al otro extremo", "en attente de l’autre côté", "in attesa dell’altro lato", "чекаю на іншу сторону";
LatencyPlot: "opóźnienie", "latency", "Verzögerung", "latencia", "latence", "latenza", "затримка";
LossPlot: "straty", "loss", "Verluste", "pérdidas", "pertes", "perdite", "втрати";
Details: "Szczegóły", "Details", "Details", "Detalles", "Détails", "Dettagli", "Подробиці";
SinkAutoHint: "W Linuksie tworzy mikrofon „MicBridge”; w Windows szuka wirtualnego kabla wśród wyjść.", "On Linux it creates a “MicBridge” microphone; on Windows it looks for a virtual cable among the outputs.", "Unter Linux entsteht ein Mikrofon „MicBridge“; unter Windows wird ein virtuelles Kabel unter den Ausgaben gesucht.", "En Linux crea un micrófono «MicBridge»; en Windows busca un cable virtual entre las salidas.", "Sous Linux, crée un microphone « MicBridge » ; sous Windows, cherche un câble virtuel parmi les sorties.", "Su Linux crea un microfono «MicBridge»; su Windows cerca un cavo virtuale tra le uscite.", "У Linux створює мікрофон «MicBridge»; у Windows шукає віртуальний кабель серед виходів.";
SinkAutoLinux: "automatycznie (mikrofon MicBridge)", "automatic (MicBridge microphone)", "automatisch (MicBridge-Mikrofon)", "automático (micrófono MicBridge)", "automatique (microphone MicBridge)", "automatico (microfono MicBridge)", "автоматично (мікрофон MicBridge)";
SinkAutoWindows: "automatycznie (wirtualny kabel)", "automatic (virtual cable)", "automatisch (virtuelles Kabel)", "automático (cable virtual)", "automatique (câble virtuel)", "automatico (cavo virtuale)", "автоматично (віртуальний кабель)";
DefaultDevice: "domyślny w systemie", "system default", "Systemstandard", "predeterminado del sistema", "par défaut du système", "predefinito di sistema", "типовий у системі";
TestTone: "ton próbny 440 Hz", "440 Hz test tone", "440-Hz-Testton", "tono de prueba de 440 Hz", "tonalité de test 440 Hz", "tono di prova a 440 Hz", "тестовий тон 440 Гц";
TestToneHint: "Sprawdza całą ścieżkę bez mikrofonu.", "Tests the whole path without a microphone.", "Prüft den gesamten Weg ohne Mikrofon.", "Comprueba todo el recorrido sin micrófono.", "Teste tout le trajet sans microphone.", "Verifica l’intero percorso senza microfono.", "Перевіряє весь шлях без мікрофона.";

// --- parowanie --------------------------------------------------------------
PairWants: "„{}” chce się sparować. Przepisz tam ten kod:", "“{}” wants to pair. Type this code there:", "„{}“ möchte sich koppeln. Gib dort diesen Code ein:", "«{}» quiere emparejarse. Escribe allí este código:", "« {} » veut s’appairer. Saisissez ce code là-bas :", "«{}» vuole associarsi. Digita là questo codice:", "«{}» хоче спаруватися. Введіть там цей код:";
PairShows: "„{}” pokazuje sześciocyfrowy kod. Przepisz go tutaj:", "“{}” is showing a six-digit code. Type it here:", "„{}“ zeigt einen sechsstelligen Code. Gib ihn hier ein:", "«{}» muestra un código de seis dígitos. Escríbelo aquí:", "« {} » affiche un code à six chiffres. Saisissez-le ici :", "«{}» mostra un codice di sei cifre. Digitalo qui:", "«{}» показує шестизначний код. Введіть його тут:";
Hide: "Schowaj", "Hide", "Ausblenden", "Ocultar", "Masquer", "Nascondi", "Сховати";
PairButton: "Sparuj", "Pair", "Koppeln", "Emparejar", "Appairer", "Associa", "Спарувати";
CancelButton: "Rezygnuję", "Cancel", "Abbrechen", "Cancelar", "Annuler", "Annulla", "Скасувати";
DigitsOf: "{} z {} cyfr", "{} of {} digits", "{} von {} Ziffern", "{} de {} dígitos", "{} sur {} chiffres", "{} di {} cifre", "{} з {} цифр";

// --- liczby pod wykresami ---------------------------------------------------
NumCushion: "poduszka", "cushion", "Polster", "colchón", "coussin", "cuscinetto", "подушка";
NumCard: "karta", "card", "Karte", "tarjeta", "carte", "scheda", "картка";
NumJitter: "jitter", "jitter", "Jitter", "fluctuación", "gigue", "jitter", "джитер";
NumFec: "FEC", "FEC", "FEC", "FEC", "FEC", "FEC", "FEC";
NumDrift: "dryf", "drift", "Drift", "deriva", "dérive", "deriva", "дрейф";
NumDropped: "wyrzucone", "dropped", "verworfen", "descartadas", "abandonnées", "scartati", "відкинуті";
NumStarved: "niedomiar", "underrun", "Unterlauf", "falta de datos", "sous-alimentation", "underrun", "нестача";
NumBitrate: "przepływność", "bitrate", "Bitrate", "tasa de bits", "débit", "bitrate", "бітрейт";
NumPeak: "szczyt", "peak", "Spitze", "pico", "crête", "picco", "пік";
NumFecFor: "FEC na", "FEC for", "FEC für", "FEC para", "FEC pour", "FEC per", "FEC на";
NumFrames: "ramek", "frames", "Frames", "tramas", "trames", "frame", "кадрів";
NumLost: "zgubione", "lost", "verloren", "perdidas", "perdus", "perse", "загублені";
FramesN: "{} ramek", "{} frames", "{} Frames", "{} tramas", "{} trames", "{} frame", "{} кадрів";
SamplesN: "{} próbek", "{} samples", "{} Samples", "{} muestras", "{} échantillons", "{} campioni", "{} семплів";
PctLoss: "{}% strat", "{}% loss", "{} % Verlust", "{} % de pérdida", "{} % de perte", "{}% di perdita", "{}% втрат";
NobodyListening: "czekam — nikt jeszcze nie słucha tego mikrofonu", "waiting — nobody is listening to this microphone yet", "warte — noch hört niemand dieses Mikrofon", "esperando: aún nadie escucha este micrófono", "en attente — personne n’écoute encore ce microphone", "in attesa: nessuno ascolta ancora questo microfono", "чекаю — цей мікрофон іще ніхто не слухає";
LatencyLoss: "opóźnienie {} ms, strat {}%", "latency {} ms, loss {}%", "Verzögerung {} ms, Verlust {} %", "latencia {} ms, pérdida {} %", "latence {} ms, perte {} %", "latenza {} ms, perdita {}%", "затримка {} мс, втрати {}%";

// --- zasobnik ---------------------------------------------------------------
ShowWindow: "Pokaż okno", "Show window", "Fenster anzeigen", "Mostrar ventana", "Afficher la fenêtre", "Mostra finestra", "Показати вікно";
Quit: "Zakończ", "Quit", "Beenden", "Salir", "Quitter", "Esci", "Вийти";

// --- wiersz poleceń: przebieg sesji -----------------------------------------
CliWaiting: "  czekam — nikt jeszcze nie słucha", "  waiting — nobody is listening yet", "  warte — noch hört niemand zu", "  esperando: aún nadie escucha", "  en attente — personne n’écoute encore", "  in attesa: nessuno ascolta ancora", "  чекаю — іще ніхто не слухає";
CliBuf: "bufor", "buffer", "Puffer", "búfer", "tampon", "buffer", "буфер";
CliTarget: "cel", "target", "Ziel", "objetivo", "cible", "obiettivo", "ціль";
CliLoss: "strat", "loss", "Verlust", "pérdida", "perte", "perdita", "втрати";
CliDrift: "dryf", "drift", "Drift", "deriva", "dérive", "deriva", "дрейф";
CliStarved: "   NIEDOMIAR {}", "   UNDERRUN {}", "   UNTERLAUF {}", "   FALTA DE DATOS {}", "   SOUS-ALIMENTATION {}", "   UNDERRUN {}", "   НЕСТАЧА {}";
CliDroppedFull: "   WYRZUCONO {} ramek (bufor pełny)", "   DROPPED {} frames (buffer full)", "   {} FRAMES VERWORFEN (Puffer voll)", "   DESCARTADAS {} tramas (búfer lleno)", "   {} TRAMES ABANDONNÉES (tampon plein)", "   SCARTATI {} frame (buffer pieno)", "   ВІДКИНУТО {} кадрів (буфер повний)";
CliBoth: "   NIEDOMIAR {}   WYRZUCONO {}", "   UNDERRUN {}   DROPPED {}", "   UNTERLAUF {}   VERWORFEN {}", "   FALTA DE DATOS {}   DESCARTADAS {}", "   SOUS-ALIMENTATION {}   ABANDONNÉES {}", "   UNDERRUN {}   SCARTATI {}", "   НЕСТАЧА {}   ВІДКИНУТО {}";
CliFecFor: "   FEC na {}% strat", "   FEC for {}% loss", "   FEC für {} % Verlust", "   FEC para {} % de pérdida", "   FEC pour {} % de perte", "   FEC per {}% di perdita", "   FEC на {}% втрат";
CliLostSamples: "   zgubiono {} próbek", "   lost {} samples", "   {} Samples verloren", "   {} muestras perdidas", "   {} échantillons perdus", "   {} campioni persi", "   загублено {} семплів";
CliDroppedOnPurpose: "   zgubiono celowo {}", "   dropped {} on purpose", "   {} absichtlich verworfen", "   {} descartados a propósito", "   {} abandonnés volontairement", "   {} scartati di proposito", "   навмисно відкинуто {}";
CliFramesWord: "ramek", "frames", "Frames", "tramas", "trames", "frame", "кадрів";
CliPeakWord: "szczyt", "peak", "Spitze", "pico", "crête", "picco", "пік";
CliCtrlC: "Ctrl-C kończy.", "Ctrl-C quits.", "Strg-C beendet.", "Ctrl-C termina.", "Ctrl-C quitte.", "Ctrl-C termina.", "Ctrl-C завершує.";

// --- wiersz poleceń: parowanie ----------------------------------------------
CliWantsPair: "„{}” prosi o sparowanie.", "“{}” is asking to pair.", "„{}“ bittet um Kopplung.", "«{}» pide emparejarse.", "« {} » demande à s’appairer.", "«{}» chiede di associarsi.", "«{}» просить спарування.";
CliCode: "  KOD: {}", "  CODE: {}", "  CODE: {}", "  CÓDIGO: {}", "  CODE : {}", "  CODICE: {}", "  КОД: {}";
CliTypeOnOther: "  Przepisz go na drugiej maszynie.", "  Type it on the other machine.", "  Gib ihn auf der anderen Maschine ein.", "  Escríbelo en la otra máquina.", "  Saisissez-le sur l’autre machine.", "  Digitalo sull’altra macchina.", "  Введіть його на іншій машині.";
CliNotPaired: "„{}” nie jest jeszcze sparowany.", "“{}” is not paired yet.", "„{}“ ist noch nicht gekoppelt.", "«{}» aún no está emparejado.", "« {} » n’est pas encore appairé.", "«{}» non è ancora associato.", "«{}» іще не спаровано.";
CliCodeOnScreen: "Na jego ekranie pojawił się sześciocyfrowy kod.", "A six-digit code has appeared on its screen.", "Auf dessen Bildschirm ist ein sechsstelliger Code erschienen.", "En su pantalla ha aparecido un código de seis dígitos.", "Un code à six chiffres est apparu sur son écran.", "Sul suo schermo è comparso un codice di sei cifre.", "На його екрані з’явився шестизначний код.";
CliTypeHere: "Przepisz go tutaj: ", "Type it here: ", "Gib ihn hier ein: ", "Escríbelo aquí: ", "Saisissez-le ici : ", "Digitalo qui: ", "Введіть його тут: ";

// --- wiersz poleceń: wykrywanie i listy -------------------------------------
CliSearching: "Szukam odbiorników przez {} ms…", "Looking for receivers for {} ms…", "Suche {} ms lang nach Empfängern…", "Buscando receptores durante {} ms…", "Recherche de récepteurs pendant {} ms…", "Cerco ricevitori per {} ms…", "Шукаю приймачі протягом {} мс…";
CliNothingSeen: "Nic nie widzę.", "I can’t see anything.", "Ich sehe nichts.", "No veo nada.", "Je ne vois rien.", "Non vedo nulla.", "Нічого не бачу.";
CliHintRecv: "  • czy na drugiej maszynie działa `micbridge recv`?", "  • is `micbridge recv` running on the other machine?", "  • läuft auf der anderen Maschine `micbridge recv`?", "  • ¿está `micbridge recv` en marcha en la otra máquina?", "  • `micbridge recv` tourne-t-il sur l’autre machine ?", "  • `micbridge recv` è in esecuzione sull’altra macchina?", "  • чи працює на іншій машині `micbridge recv`?";
CliHintSameNet: "  • czy obie są w tej samej sieci?", "  • are both on the same network?", "  • sind beide im selben Netzwerk?", "  • ¿están ambas en la misma red?", "  • sont-elles sur le même réseau ?", "  • sono entrambe sulla stessa rete?", "  • чи обидві в одній мережі?";
CliHintMulticast: "  • część routerów Wi-Fi blokuje ruch multicast między klientami;", "  • some Wi-Fi routers block multicast between clients;", "  • manche WLAN-Router blockieren Multicast zwischen Clients;", "  • algunos routers Wi-Fi bloquean el multicast entre clientes;", "  • certains routeurs Wi-Fi bloquent le multicast entre clients ;", "  • alcuni router Wi-Fi bloccano il multicast tra client;", "  • деякі Wi-Fi-роутери блокують багатоадресний трафік між клієнтами;";
CliHintUseTo: "    wtedy zostaje `send --to 192.168.1.40`.", "    then `send --to 192.168.1.40` is the way.", "    dann bleibt `send --to 192.168.1.40`.", "    entonces queda `send --to 192.168.1.40`.", "    il reste alors `send --to 192.168.1.40`.", "    allora resta `send --to 192.168.1.40`.", "    тоді залишається `send --to 192.168.1.40`.";
CliReceivers: "ODBIORNIKI", "RECEIVERS", "EMPFÄNGER", "RECEPTORES", "RÉCEPTEURS", "RICEVITORI", "ПРИЙМАЧІ";
CliProtocolInstead: "  ← protokół {} zamiast {}", "  ← protocol {} instead of {}", "  ← Protokoll {} statt {}", "  ← protocolo {} en lugar de {}", "  ← protocole {} au lieu de {}", "  ← protocollo {} invece di {}", "  ← протокол {} замість {}";
CliSendWith: "Wysyłanie: micbridge send --to „{}”", "To send: micbridge send --to “{}”", "Senden: micbridge send --to „{}“", "Para enviar: micbridge send --to «{}»", "Pour envoyer : micbridge send --to « {} »", "Per inviare: micbridge send --to «{}»", "Надсилання: micbridge send --to «{}»";
CliPairedHeading: "SPAROWANE", "PAIRED", "GEKOPPELT", "EMPAREJADOS", "APPAIRÉS", "ASSOCIATI", "СПАРОВАНІ";
CliNothingPaired: "Nic jeszcze nie sparowane.", "Nothing paired yet.", "Noch nichts gekoppelt.", "Aún no hay nada emparejado.", "Rien n’est encore appairé.", "Nulla è ancora associato.", "Іще нічого не спаровано.";
CliPairingIsAutomatic: "Parowanie dzieje się samo przy pierwszym połączeniu.", "Pairing happens on its own at the first connection.", "Die Kopplung geschieht von selbst bei der ersten Verbindung.", "El emparejamiento ocurre solo en la primera conexión.", "L’appairage se fait tout seul à la première connexion.", "L’associazione avviene da sola alla prima connessione.", "Спарування відбувається саме при першому з’єднанні.";
CliKeysAt: "Klucze: {}", "Keys: {}", "Schlüssel: {}", "Claves: {}", "Clés : {}", "Chiavi: {}", "Ключі: {}";
CliForgetHint: "Zapomnienie: micbridge forget <nazwa> — po obu stronach.", "To forget: micbridge forget <name> — on both sides.", "Vergessen: micbridge forget <name> — auf beiden Seiten.", "Para olvidar: micbridge forget <nombre> — en ambos lados.", "Pour oublier : micbridge forget <nom> — des deux côtés.", "Per dimenticare: micbridge forget <nome> — su entrambi i lati.", "Забути: micbridge forget <назва> — з обох боків.";
CliForgotten: "Zapomniane: „{}”.", "Forgotten: “{}”.", "Vergessen: „{}“.", "Olvidado: «{}».", "Oublié : « {} ».", "Dimenticato: «{}».", "Забуто: «{}».";
CliForgetOther: "Zrób to samo po drugiej stronie, inaczej nie dogadacie się bez kodu.", "Do the same on the other side, or you will not agree without a code.", "Mach dasselbe auf der Gegenseite, sonst kommt ihr ohne Code nicht zusammen.", "Haz lo mismo en el otro lado o no os entenderéis sin código.", "Faites de même de l’autre côté, sinon vous ne vous entendrez pas sans code.", "Fai lo stesso dall’altro lato, altrimenti non vi intenderete senza codice.", "Зробіть те саме з іншого боку, інакше без коду не домовитесь.";
CliNothingUnder: "Nie mam nic zapisanego pod „{}”.", "I have nothing stored under “{}”.", "Unter „{}“ ist nichts gespeichert.", "No tengo nada guardado bajo «{}».", "Je n’ai rien d’enregistré sous « {} ».", "Non ho nulla salvato sotto «{}».", "Під «{}» нічого не збережено.";
CliInputs: "WEJŚCIA (źródła mikrofonu)", "INPUTS (microphone sources)", "EINGÄNGE (Mikrofonquellen)", "ENTRADAS (fuentes de micrófono)", "ENTRÉES (sources de microphone)", "INGRESSI (sorgenti microfono)", "ВХОДИ (джерела мікрофона)";
CliOutputs: "WYJŚCIA (ujścia — tu szukamy wirtualnego kabla)", "OUTPUTS (sinks — this is where the virtual cable lives)", "AUSGÄNGE (Senken — hier suchen wir das virtuelle Kabel)", "SALIDAS (sumideros: aquí buscamos el cable virtual)", "SORTIES (puits — c’est ici qu’on cherche le câble virtuel)", "USCITE (destinazioni: qui cerchiamo il cavo virtuale)", "ВИХОДИ (стоки — тут шукаємо віртуальний кабель)";
CliNone: "  (brak)", "  (none)", "  (keine)", "  (ninguno)", "  (aucun)", "  (nessuno)", "  (немає)";
CliVirtualCable: "  ← wirtualny kabel", "  ← virtual cable", "  ← virtuelles Kabel", "  ← cable virtual", "  ← câble virtuel", "  ← cavo virtuale", "  ← віртуальний кабель";

// --- przegląd gotowości -----------------------------------------------------
DocTitle: "MicBridge — przegląd", "MicBridge — check-up", "MicBridge — Überblick", "MicBridge — revisión", "MicBridge — bilan", "MicBridge — verifica", "MicBridge — огляд";
DocAllGood: "Wszystko na miejscu.", "Everything is in place.", "Alles an seinem Platz.", "Todo está en su sitio.", "Tout est en place.", "Tutto a posto.", "Усе на місці.";
DocPartial: "Da się pracować, ale nie wszystkie role są dostępne.", "Usable, but not every role is available.", "Nutzbar, aber nicht jede Rolle steht bereit.", "Se puede trabajar, pero no todos los papeles están disponibles.", "Utilisable, mais tous les rôles ne sont pas disponibles.", "Si può lavorare, ma non tutti i ruoli sono disponibili.", "Працювати можна, але не всі ролі доступні.";
DocBroken: "Coś jest nie tak — patrz wskazówki wyżej.", "Something is wrong — see the advice above.", "Etwas stimmt nicht — siehe Hinweise oben.", "Algo va mal: mira los consejos de arriba.", "Quelque chose ne va pas — voir les conseils ci-dessus.", "Qualcosa non va: vedi i suggerimenti sopra.", "Щось не так — див. поради вище.";
DocMic: "mikrofon", "microphone", "Mikrofon", "micrófono", "microphone", "microfono", "мікрофон";
DocVirtualInput: "wejście wirtualne", "virtual input", "virtueller Eingang", "entrada virtual", "entrée virtuelle", "ingresso virtuale", "віртуальний вхід";
DocPairing: "parowanie", "pairing", "Kopplung", "emparejamiento", "appairage", "associazione", "спарування";
DevicesOne: "urządzenie", "device", "Gerät", "dispositivo", "périphérique", "dispositivo", "пристрій";
DevicesFew: "urządzenia", "devices", "Geräte", "dispositivos", "périphériques", "dispositivi", "пристрої";
DevicesMany: "urządzeń", "devices", "Geräte", "dispositivos", "périphériques", "dispositivi", "пристроїв";
DocDefaultIs: "{}, domyślne: {}", "{}, default: {}", "{}, Standard: {}", "{}, predeterminado: {}", "{}, par défaut : {}", "{}, predefinito: {}", "{}, типовий: {}";
DocNoInput: "system nie pokazuje żadnego wejścia", "the system shows no input at all", "das System zeigt keinerlei Eingang", "el sistema no muestra ninguna entrada", "le système n’affiche aucune entrée", "il sistema non mostra alcun ingresso", "система не показує жодного входу";
DocNoInputAdvice: "Ta maszyna może tylko odbierać. Do sprawdzenia ścieżki bez mikrofonu jest `--device tone`.", "This machine can only receive. To test the path without a microphone there is `--device tone`.", "Diese Maschine kann nur empfangen. Zum Prüfen ohne Mikrofon gibt es `--device tone`.", "Esta máquina solo puede recibir. Para probar el camino sin micrófono está `--device tone`.", "Cette machine ne peut que recevoir. Pour tester sans microphone, il y a `--device tone`.", "Questa macchina può solo ricevere. Per provare il percorso senza microfono c’è `--device tone`.", "Ця машина може лише приймати. Щоб перевірити шлях без мікрофона, є `--device tone`.";
DocCannotQuery: "nie mogę odpytać systemu: {}", "cannot query the system: {}", "kann das System nicht abfragen: {}", "no puedo consultar al sistema: {}", "impossible d’interroger le système : {}", "non riesco a interrogare il sistema: {}", "не можу опитати систему: {}";
DocCheckAudio: "Sprawdź, czy działa podsystem dźwięku.", "Check that the audio subsystem is running.", "Prüfe, ob das Audiosystem läuft.", "Comprueba que el subsistema de audio funcione.", "Vérifiez que le sous-système audio fonctionne.", "Controlla che il sottosistema audio sia attivo.", "Перевірте, чи працює звукова підсистема.";
DocPipewireOk: "PipeWire działa — mikrofon „MicBridge” powstaje sam", "PipeWire is running — the “MicBridge” microphone appears on its own", "PipeWire läuft — das Mikrofon „MicBridge“ entsteht von selbst", "PipeWire funciona: el micrófono «MicBridge» aparece solo", "PipeWire fonctionne — le microphone « MicBridge » apparaît tout seul", "PipeWire è attivo: il microfono «MicBridge» compare da solo", "PipeWire працює — мікрофон «MicBridge» з’являється сам";
DocNoPipewire: "nie widzę PipeWire", "I cannot see PipeWire", "PipeWire nicht gefunden", "no veo PipeWire", "PipeWire introuvable", "non vedo PipeWire", "не бачу PipeWire";
DocNoPipewireAdvice: "Odbieranie wymaga PipeWire: `systemctl --user status pipewire wireplumber`. Na czystym PulseAudio wskaż ujście przez --sink.", "Receiving needs PipeWire: `systemctl --user status pipewire wireplumber`. On plain PulseAudio point at a sink with --sink.", "Empfangen braucht PipeWire: `systemctl --user status pipewire wireplumber`. Bei reinem PulseAudio die Senke mit --sink angeben.", "Recibir requiere PipeWire: `systemctl --user status pipewire wireplumber`. Con PulseAudio puro, indica el sumidero con --sink.", "La réception exige PipeWire : `systemctl --user status pipewire wireplumber`. Sur PulseAudio pur, indiquez le puits avec --sink.", "La ricezione richiede PipeWire: `systemctl --user status pipewire wireplumber`. Con PulseAudio puro indica la destinazione con --sink.", "Приймання потребує PipeWire: `systemctl --user status pipewire wireplumber`. На чистому PulseAudio вкажіть стік через --sink.";
DocCableReady: "{} — gotowe", "{} — ready", "{} — bereit", "{} — listo", "{} — prêt", "{} — pronto", "{} — готово";
DocNoCable: "brak wirtualnego kabla", "no virtual cable", "kein virtuelles Kabel", "falta el cable virtual", "pas de câble virtuel", "nessun cavo virtuale", "немає віртуального кабелю";
DocNoCableAdvice: "Potrzebny tylko do ODBIERANIA — żeby cudzy mikrofon pojawił się tu jako urządzenie.\n    Zainstaluj VB-CABLE (https://vb-audio.com/Cable/) i ustaw w nim Max Latency na 2048.\n    Do samego wysyłania nie jest potrzebny.", "Needed only for RECEIVING — so someone else’s microphone shows up here as a device.\n    Install VB-CABLE (https://vb-audio.com/Cable/) and set its Max Latency to 2048.\n    Sending alone does not need it.", "Nur zum EMPFANGEN nötig — damit ein fremdes Mikrofon hier als Gerät erscheint.\n    Installiere VB-CABLE (https://vb-audio.com/Cable/) und setze dort Max Latency auf 2048.\n    Zum reinen Senden wird es nicht gebraucht.", "Solo hace falta para RECIBIR: para que el micrófono ajeno aparezca aquí como dispositivo.\n    Instala VB-CABLE (https://vb-audio.com/Cable/) y pon Max Latency en 2048.\n    Para enviar no es necesario.", "Nécessaire uniquement pour la RÉCEPTION — pour que le microphone d’en face apparaisse ici comme périphérique.\n    Installez VB-CABLE (https://vb-audio.com/Cable/) et réglez Max Latency sur 2048.\n    L’envoi seul n’en a pas besoin.", "Serve solo per la RICEZIONE — perché il microfono altrui compaia qui come dispositivo.\n    Installa VB-CABLE (https://vb-audio.com/Cable/) e imposta Max Latency a 2048.\n    Per il solo invio non serve.", "Потрібен лише для ПРИЙМАННЯ — щоб чужий мікрофон з’явився тут як пристрій.\n    Встановіть VB-CABLE (https://vb-audio.com/Cable/) і задайте Max Latency 2048.\n    Для самого надсилання він не потрібен.";
DocNothingPaired: "nic jeszcze nie sparowane", "nothing paired yet", "noch nichts gekoppelt", "aún nada emparejado", "rien d’appairé pour l’instant", "nulla ancora associato", "іще нічого не спаровано";
DocNothingPairedAdvice: "Dzieje się samo przy pierwszym połączeniu: odbiornik pokaże kod, nadajnik o niego poprosi.", "It happens on its own at the first connection: the receiver shows a code, the sender asks for it.", "Geschieht von selbst bei der ersten Verbindung: der Empfänger zeigt einen Code, der Sender fragt danach.", "Ocurre solo en la primera conexión: el receptor muestra un código y el emisor lo pide.", "Cela se fait tout seul à la première connexion : le récepteur affiche un code, l’émetteur le demande.", "Avviene da solo alla prima connessione: il ricevitore mostra un codice, il mittente lo chiede.", "Відбувається саме при першому з’єднанні: приймач покаже код, передавач його попросить.";
DocCannotReadKeys: "nie mogę odczytać kluczy: {}", "cannot read the keys: {}", "kann die Schlüssel nicht lesen: {}", "no puedo leer las claves: {}", "impossible de lire les clés : {}", "non riesco a leggere le chiavi: {}", "не можу прочитати ключі: {}";
DocCheckConfigDir: "Sprawdź prawa do katalogu konfiguracyjnego.", "Check the permissions on the configuration directory.", "Prüfe die Rechte am Konfigurationsverzeichnis.", "Comprueba los permisos del directorio de configuración.", "Vérifiez les droits sur le répertoire de configuration.", "Controlla i permessi della cartella di configurazione.", "Перевірте права на теку конфігурації.";
// --- wiersz poleceń: pomoc --------------------------------------------------
CliAbout: "Mikrofon z jednego komputera na drugim", "One computer’s microphone on another", "Das Mikrofon eines Rechners auf einem anderen", "El micrófono de un ordenador en otro", "Le microphone d’un ordinateur sur un autre", "Il microfono di un computer su un altro", "Мікрофон одного комп’ютера на іншому";
HelpVerbose: "Więcej logów (można powtórzyć: -vv).", "More logging (repeatable: -vv).", "Mehr Protokoll (wiederholbar: -vv).", "Más registro (repetible: -vv).", "Plus de journalisation (répétable : -vv).", "Più log (ripetibile: -vv).", "Більше журналу (можна повторити: -vv).";
HelpDevices: "Wypisz urządzenia audio widoczne w systemie.", "List the audio devices the system shows.", "Die vom System angezeigten Audiogeräte auflisten.", "Listar los dispositivos de audio que muestra el sistema.", "Lister les périphériques audio vus par le système.", "Elenca i dispositivi audio visti dal sistema.", "Показати звукові пристрої, які бачить система.";
HelpDoctor: "Sprawdź, czy ta maszyna jest gotowa wysyłać i odbierać.", "Check whether this machine is ready to send and to receive.", "Prüfen, ob diese Maschine senden und empfangen kann.", "Comprobar si esta máquina puede enviar y recibir.", "Vérifier si cette machine peut émettre et recevoir.", "Verifica se questa macchina può inviare e ricevere.", "Перевірити, чи готова ця машина надсилати й приймати.";
HelpPeers: "Wypisz sparowane maszyny.", "List the paired machines.", "Die gekoppelten Maschinen auflisten.", "Listar las máquinas emparejadas.", "Lister les machines appairées.", "Elenca le macchine associate.", "Показати спаровані машини.";
HelpForget: "Zapomnij parowanie z podaną maszyną.", "Forget the pairing with the given machine.", "Die Kopplung mit der angegebenen Maschine vergessen.", "Olvidar el emparejamiento con la máquina indicada.", "Oublier l’appairage avec la machine indiquée.", "Dimentica l’associazione con la macchina indicata.", "Забути спарування із зазначеною машиною.";
HelpForgetPeer: "Nazwa z listy `peers`.", "A name from the `peers` list.", "Ein Name aus der Liste `peers`.", "Un nombre de la lista `peers`.", "Un nom de la liste `peers`.", "Un nome dall’elenco `peers`.", "Назва зі списку `peers`.";
HelpDiscover: "Pokaż odbiorniki widoczne w sieci lokalnej.", "Show the receivers visible on the local network.", "Die im lokalen Netz sichtbaren Empfänger zeigen.", "Mostrar los receptores visibles en la red local.", "Afficher les récepteurs visibles sur le réseau local.", "Mostra i ricevitori visibili nella rete locale.", "Показати приймачі, видимі в локальній мережі.";
HelpWindowMs: "Jak długo słuchać odpowiedzi.", "How long to listen for answers.", "Wie lange auf Antworten gewartet wird.", "Cuánto tiempo escuchar respuestas.", "Combien de temps écouter les réponses.", "Per quanto tempo ascoltare le risposte.", "Скільки часу слухати відповіді.";
HelpSend: "Wysyłaj mikrofon do drugiego komputera.", "Send this microphone to the other computer.", "Das Mikrofon an den anderen Rechner senden.", "Enviar el micrófono al otro ordenador.", "Envoyer le microphone vers l’autre ordinateur.", "Invia il microfono all’altro computer.", "Надсилати мікрофон на інший комп’ютер.";
HelpTo: "Odbiornik: adres, `adres:port` albo nazwa z `micbridge discover`. Bez tej flagi szukamy go w sieci.", "Receiver: an address, `address:port`, or a name from `micbridge discover`. Without this flag we look for it on the network.", "Empfänger: Adresse, `adresse:port` oder ein Name aus `micbridge discover`. Ohne diese Option wird im Netz gesucht.", "Receptor: una dirección, `dirección:puerto` o un nombre de `micbridge discover`. Sin esta opción lo buscamos en la red.", "Récepteur : une adresse, `adresse:port` ou un nom issu de `micbridge discover`. Sans cette option, on le cherche sur le réseau.", "Ricevitore: un indirizzo, `indirizzo:porta` o un nome da `micbridge discover`. Senza questa opzione lo cerchiamo in rete.", "Приймач: адреса, `адреса:порт` або назва з `micbridge discover`. Без цього прапорця шукаємо його в мережі.";
HelpDevice: "Źródło: `default`, `@3` albo fragment nazwy, np. `yeti`.", "Source: `default`, `@3`, or part of a name, e.g. `yeti`.", "Quelle: `default`, `@3` oder ein Namensteil, z. B. `yeti`.", "Fuente: `default`, `@3` o parte de un nombre, p. ej. `yeti`.", "Source : `default`, `@3` ou une partie du nom, p. ex. `yeti`.", "Sorgente: `default`, `@3` o parte di un nome, ad es. `yeti`.", "Джерело: `default`, `@3` або частина назви, напр. `yeti`.";
HelpGain: "Wzmocnienie w decybelach, dodatnie podbija cichy mikrofon.", "Gain in decibels; positive values lift a quiet microphone.", "Verstärkung in Dezibel; positive Werte heben ein leises Mikrofon an.", "Ganancia en decibelios; los valores positivos suben un micrófono flojo.", "Gain en décibels ; les valeurs positives relèvent un microphone trop faible.", "Guadagno in decibel; i valori positivi alzano un microfono debole.", "Підсилення в децибелах; додатні значення піднімають тихий мікрофон.";
HelpBitrate: "Przepływność Opusa. 24 kbps jest przezroczyste dla mowy.", "Opus bitrate. 24 kbps is transparent for speech.", "Opus-Bitrate. 24 kbps ist für Sprache transparent.", "Tasa de bits de Opus. 24 kbps es transparente para la voz.", "Débit Opus. 24 kbit/s est transparent pour la parole.", "Bitrate Opus. 24 kbps è trasparente per il parlato.", "Бітрейт Opus. 24 кбіт/с прозорий для мовлення.";
HelpDropPct: "Diagnostyka: gub celowo tyle procent pakietów, żeby sprawdzić FEC.", "Diagnostics: drop this percentage of packets on purpose to exercise FEC.", "Diagnose: absichtlich so viel Prozent der Pakete verwerfen, um FEC zu prüfen.", "Diagnóstico: descartar a propósito ese porcentaje de paquetes para probar el FEC.", "Diagnostic : abandonner volontairement ce pourcentage de paquets pour éprouver le FEC.", "Diagnostica: scarta di proposito questa percentuale di pacchetti per provare il FEC.", "Діагностика: навмисно відкидати стільки відсотків пакетів, щоб перевірити FEC.";
HelpCode: "Kod parowania, gdy nie ma gdzie go wpisać (skrypty, usługi).", "Pairing code for when there is nowhere to type it (scripts, services).", "Kopplungscode, wenn niemand ihn eintippen kann (Skripte, Dienste).", "Código de emparejamiento cuando no hay dónde escribirlo (guiones, servicios).", "Code d’appairage quand il n’y a personne pour le saisir (scripts, services).", "Codice di associazione quando non c’è dove digitarlo (script, servizi).", "Код спарування, коли його немає де ввести (скрипти, служби).";
HelpRecv: "Odbieraj mikrofon i wpuszczaj go w wirtualne urządzenie.", "Receive a microphone and feed it into a virtual device.", "Ein Mikrofon empfangen und in ein virtuelles Gerät einspeisen.", "Recibir un micrófono y volcarlo en un dispositivo virtual.", "Recevoir un microphone et l’injecter dans un périphérique virtuel.", "Ricevi un microfono e immettilo in un dispositivo virtuale.", "Приймати мікрофон і подавати його у віртуальний пристрій.";
HelpListen: "Interfejs i port do nasłuchu.", "Interface and port to listen on.", "Schnittstelle und Port zum Lauschen.", "Interfaz y puerto donde escuchar.", "Interface et port d’écoute.", "Interfaccia e porta su cui ascoltare.", "Інтерфейс і порт для прослуховування.";
HelpSink: "Ujście: `auto` (Linux: własny mikrofon, Windows: wirtualny kabel), `virtual`, `device` albo fragment nazwy urządzenia.", "Sink: `auto` (Linux: our own microphone, Windows: a virtual cable), `virtual`, `device`, or part of a device name.", "Senke: `auto` (Linux: eigenes Mikrofon, Windows: virtuelles Kabel), `virtual`, `device` oder ein Namensteil.", "Sumidero: `auto` (Linux: micrófono propio, Windows: cable virtual), `virtual`, `device` o parte de un nombre.", "Puits : `auto` (Linux : notre propre microphone, Windows : câble virtuel), `virtual`, `device` ou une partie du nom.", "Destinazione: `auto` (Linux: microfono nostro, Windows: cavo virtuale), `virtual`, `device` o parte di un nome.", "Стік: `auto` (Linux: власний мікрофон, Windows: віртуальний кабель), `virtual`, `device` або частина назви.";
HelpBufferMs: "Startowa głębokość bufora jitter.", "Starting depth of the jitter buffer.", "Anfangstiefe des Jitter-Puffers.", "Profundidad inicial del búfer de fluctuación.", "Profondeur initiale du tampon de gigue.", "Profondità iniziale del buffer di jitter.", "Початкова глибина буфера джитера.";
HelpFixedBuffer: "Nie dopasowuj poduszki do jakości łącza — trzymaj zadaną wartość.", "Do not adapt the cushion to the link — hold the given value.", "Das Polster nicht an die Verbindung anpassen — den Wert halten.", "No adaptar el colchón al enlace: mantener el valor dado.", "Ne pas adapter le coussin à la liaison — garder la valeur donnée.", "Non adattare il cuscinetto al collegamento: mantieni il valore dato.", "Не підлаштовувати подушку під канал — тримати задане значення.";
HelpNoAnnounce: "Nie ogłaszaj się w sieci — druga strona poda adres.", "Do not announce on the network — the other side will supply the address.", "Nicht im Netz ankündigen — die Gegenseite gibt die Adresse an.", "No anunciarse en la red: el otro extremo dará la dirección.", "Ne pas s’annoncer sur le réseau — l’autre côté fournira l’adresse.", "Non annunciarsi in rete: l’altro lato indicherà l’indirizzo.", "Не оголошуватися в мережі — інша сторона вкаже адресу.";
VnName: "NAZWA", "NAME", "NAME", "NOMBRE", "NOM", "NOME", "НАЗВА";
VnAddress: "ADRES", "ADDRESS", "ADRESSE", "DIRECCIÓN", "ADRESSE", "INDIRIZZO", "АДРЕСА";
VnDevice: "URZĄDZENIE", "DEVICE", "GERÄT", "DISPOSITIVO", "PÉRIPHÉRIQUE", "DISPOSITIVO", "ПРИСТРІЙ";
VnSink: "UJŚCIE", "SINK", "SENKE", "SUMIDERO", "PUITS", "DESTINAZIONE", "СТІК";
VnDigits: "CYFRY", "DIGITS", "ZIFFERN", "DÍGITOS", "CHIFFRES", "CIFRE", "ЦИФРИ";

// --- błędy, na które użytkownik może zareagować ------------------------------
ErrNoDeviceIdx: "nie ma urządzenia {} o indeksie {}", "there is no {} device with index {}", "es gibt kein {}-Gerät mit Index {}", "no hay ningún dispositivo {} con índice {}", "il n’y a pas de périphérique {} d’indice {}", "non esiste un dispositivo {} con indice {}", "немає пристрою {} з індексом {}";
ErrNoDefault: "system nie ma domyślnego urządzenia {}", "the system has no default {} device", "das System hat kein Standardgerät für {}", "el sistema no tiene dispositivo {} predeterminado", "le système n’a pas de périphérique {} par défaut", "il sistema non ha un dispositivo {} predefinito", "у системі немає типового пристрою {}";
ErrNoFormat: "urządzenie „{}” nie oferuje formatu f32 ani i16", "device “{}” offers neither f32 nor i16", "Gerät „{}“ bietet weder f32 noch i16", "el dispositivo «{}» no ofrece ni f32 ni i16", "le périphérique « {} » n’offre ni f32 ni i16", "il dispositivo «{}» non offre né f32 né i16", "пристрій «{}» не пропонує ні f32, ні i16";
ErrDirIn: "wejściowego", "input", "Eingabe", "de entrada", "d’entrée", "di ingresso", "входу";
ErrDirOut: "wyjściowego", "output", "Ausgabe", "de salida", "de sortie", "di uscita", "виходу";
ErrTargetNothing: "adres „{}” nie wskazuje na nic", "address “{}” points at nothing", "Adresse „{}“ zeigt auf nichts", "la dirección «{}» no apunta a nada", "l’adresse « {} » ne mène nulle part", "l’indirizzo «{}» non punta a nulla", "адреса «{}» ні на що не вказує";
ErrPeerAborted: "druga strona przerwała: {}", "the other side stopped: {}", "die Gegenseite hat abgebrochen: {}", "el otro extremo interrumpió: {}", "l’autre côté a interrompu : {}", "l’altro lato ha interrotto: {}", "інша сторона перервала: {}";
ErrPeerAbortedPairing: "druga strona przerwała parowanie: {}", "the other side stopped pairing: {}", "die Gegenseite hat die Kopplung abgebrochen: {}", "el otro extremo interrumpió el emparejamiento: {}", "l’autre côté a interrompu l’appairage : {}", "l’altro lato ha interrotto l’associazione: {}", "інша сторона перервала спарування: {}";
ErrCodeMismatch: "kod się nie zgadza", "the code does not match", "der Code stimmt nicht", "el código no coincide", "le code ne correspond pas", "il codice non corrisponde", "код не збігається";
ErrRejected: "odbiornik odrzucił połączenie: {}", "the receiver refused the connection: {}", "der Empfänger hat die Verbindung abgelehnt: {}", "el receptor rechazó la conexión: {}", "le récepteur a refusé la connexion : {}", "il ricevitore ha rifiutato la connessione: {}", "приймач відхилив з’єднання: {}";
ErrNoConfigDir: "nie wiem, gdzie trzymać konfigurację", "I do not know where to keep the configuration", "ich weiß nicht, wo die Konfiguration liegen soll", "no sé dónde guardar la configuración", "je ne sais pas où ranger la configuration", "non so dove tenere la configurazione", "не знаю, де тримати конфігурацію";
ErrMdnsAnnounce: "nie mogę ogłosić usługi mDNS: {}", "cannot announce the mDNS service: {}", "kann den mDNS-Dienst nicht ankündigen: {}", "no puedo anunciar el servicio mDNS: {}", "impossible d’annoncer le service mDNS : {}", "non riesco ad annunciare il servizio mDNS: {}", "не можу оголосити службу mDNS: {}";
ErrMdnsBrowse: "nie mogę szukać w sieci: {}", "cannot search the network: {}", "kann im Netz nicht suchen: {}", "no puedo buscar en la red: {}", "impossible de chercher sur le réseau : {}", "non riesco a cercare in rete: {}", "не можу шукати в мережі: {}";
ErrMdnsStart: "nie mogę uruchomić usługi mDNS: {}", "cannot start the mDNS service: {}", "kann den mDNS-Dienst nicht starten: {}", "no puedo iniciar el servicio mDNS: {}", "impossible de démarrer le service mDNS : {}", "non riesco ad avviare il servizio mDNS: {}", "не можу запустити службу mDNS: {}";
ErrPipewireConnect: "nie mogę połączyć się z serwerem PipeWire: {}", "cannot connect to the PipeWire server: {}", "kann keine Verbindung zum PipeWire-Server herstellen: {}", "no puedo conectar con el servidor PipeWire: {}", "impossible de se connecter au serveur PipeWire : {}", "non riesco a connettermi al server PipeWire: {}", "не можу з’єднатися із сервером PipeWire: {}";
ErrCtrlC: "nie mogę przechwycić Ctrl-C", "cannot catch Ctrl-C", "kann Strg-C nicht abfangen", "no puedo capturar Ctrl-C", "impossible d’intercepter Ctrl-C", "non riesco a intercettare Ctrl-C", "не можу перехопити Ctrl-C";
ErrReadCode: "nie mogę odczytać kodu", "cannot read the code", "kann den Code nicht lesen", "no puedo leer el código", "impossible de lire le code", "non riesco a leggere il codice", "не можу прочитати код";
ErrCodeLength: "kod ma {} cyfr, oczekuję {}", "the code has {} digits, I expect {}", "der Code hat {} Ziffern, erwartet werden {}", "el código tiene {} dígitos, espero {}", "le code a {} chiffres, j’en attends {}", "il codice ha {} cifre, ne attendo {}", "у коді {} цифр, очікую {}";
ErrPairingCancelled: "parowanie przerwane", "pairing cancelled", "Kopplung abgebrochen", "emparejamiento cancelado", "appairage annulé", "associazione annullata", "спарування скасовано";
ErrNobodyTypedCode: "nikt nie wpisał kodu", "nobody typed the code", "niemand hat den Code eingegeben", "nadie escribió el código", "personne n’a saisi le code", "nessuno ha digitato il codice", "ніхто не ввів код";
// --- przebieg sesji (widoczny i w terminalu, i w „Szczegółach” okna) ---------
SesListening: "Nasłuchuję na {}.", "Listening on {}.", "Lausche auf {}.", "Escuchando en {}.", "À l’écoute sur {}.", "In ascolto su {}.", "Слухаю на {}.";
SesVisibleAs: "Widoczny w sieci jako „{}”.", "Visible on the network as “{}”.", "Im Netzwerk sichtbar als „{}“.", "Visible en la red como «{}».", "Visible sur le réseau sous « {} ».", "Visibile in rete come «{}».", "Видимий у мережі як «{}».";
SesCannotAnnounce: "Nie mogę ogłosić się w sieci — druga strona musi podać adres ręcznie.", "I cannot announce myself on the network — the other side must give the address by hand.", "Ich kann mich im Netz nicht ankündigen — die Gegenseite muss die Adresse von Hand angeben.", "No puedo anunciarme en la red: el otro extremo tendrá que indicar la dirección a mano.", "Impossible de m’annoncer sur le réseau — l’autre côté devra saisir l’adresse à la main.", "Non riesco ad annunciarmi in rete: l’altro lato dovrà indicare l’indirizzo a mano.", "Не можу оголоситися в мережі — інша сторона має вказати адресу вручну.";
SesJitterBuffer: "Bufor jitter: {} ms ({} × {} ms){}.", "Jitter buffer: {} ms ({} × {} ms){}.", "Jitter-Puffer: {} ms ({} × {} ms){}.", "Búfer de fluctuación: {} ms ({} × {} ms){}.", "Tampon de gigue : {} ms ({} × {} ms){}.", "Buffer di jitter: {} ms ({} × {} ms){}.", "Буфер джитера: {} мс ({} × {} мс){}.";
SesAdaptive: ", adaptacyjny", ", adaptive", ", adaptiv", ", adaptativo", ", adaptatif", ", adattivo", ", адаптивний";
SesFixed: ", stały", ", fixed", ", fest", ", fijo", ", fixe", ", fisso", ", сталий";
SesEnded: "Sesja zakończona: {}", "Session ended: {}", "Sitzung beendet: {}", "Sesión terminada: {}", "Session terminée : {}", "Sessione terminata: {}", "Сеанс завершено: {}";
SesWaitNext: "Czekam na kolejne połączenie.", "Waiting for the next connection.", "Warte auf die nächste Verbindung.", "Esperando la siguiente conexión.", "En attente de la prochaine connexion.", "In attesa della prossima connessione.", "Чекаю на наступне з’єднання.";
SesSource: "{} — źródło: {}", "{} — source: {}", "{} — Quelle: {}", "{} — fuente: {}", "{} — source : {}", "{} — sorgente: {}", "{} — джерело: {}";
SesConversion: "  konwersja {} Hz → {} Hz", "  converting {} Hz → {} Hz", "  Umrechnung {} Hz → {} Hz", "  conversión {} Hz → {} Hz", "  conversion {} Hz → {} Hz", "  conversione {} Hz → {} Hz", "  перетворення {} Гц → {} Гц";
SesPickMicNamed: "  w aplikacji (Discord, OBS, gra) wybierz mikrofon „{}”", "  in the application (Discord, OBS, a game) pick the microphone “{}”", "  wähle in der Anwendung (Discord, OBS, Spiel) das Mikrofon „{}“", "  en la aplicación (Discord, OBS, un juego) elige el micrófono «{}»", "  dans l’application (Discord, OBS, un jeu), choisissez le microphone « {} »", "  nell’applicazione (Discord, OBS, un gioco) scegli il microfono «{}»", "  у програмі (Discord, OBS, гра) виберіть мікрофон «{}»";
SesPickMicDevice: "  w aplikacji wybierz mikrofon odpowiadający temu urządzeniu", "  in the application pick the microphone that matches this device", "  wähle in der Anwendung das zu diesem Gerät passende Mikrofon", "  en la aplicación elige el micrófono que corresponde a este dispositivo", "  dans l’application, choisissez le microphone correspondant à ce périphérique", "  nell’applicazione scegli il microfono corrispondente a questo dispositivo", "  у програмі виберіть мікрофон, що відповідає цьому пристрою";
SesConversionSend: "Konwersja {} Hz → {} Hz.", "Converting {} Hz → {} Hz.", "Umrechnung {} Hz → {} Hz.", "Conversión {} Hz → {} Hz.", "Conversion {} Hz → {} Hz.", "Conversione {} Hz → {} Hz.", "Перетворення {} Гц → {} Гц.";
SesDroppingOnPurpose: "UWAGA: celowo gubię {}% pakietów (tryb diagnostyczny).", "NOTE: dropping {}% of packets on purpose (diagnostic mode).", "ACHTUNG: verwerfe absichtlich {} % der Pakete (Diagnosemodus).", "AVISO: descarto a propósito el {} % de los paquetes (modo diagnóstico).", "ATTENTION : j’abandonne volontairement {} % des paquets (mode diagnostic).", "ATTENZIONE: scarto di proposito il {}% dei pacchetti (modalità diagnostica).", "УВАГА: навмисно відкидаю {}% пакетів (діагностичний режим).";
SesOpusAt: "Nadaję Opusem, {} kbps.", "Sending with Opus, {} kbps.", "Sende mit Opus, {} kbps.", "Enviando con Opus, {} kbps.", "Émission en Opus, {} kbit/s.", "Invio con Opus, {} kbps.", "Передаю через Opus, {} кбіт/с.";
SesDone: "Zakończono. Wysłano {} ramek.", "Finished. {} frames sent.", "Fertig. {} Frames gesendet.", "Terminado. {} tramas enviadas.", "Terminé. {} trames envoyées.", "Finito. {} frame inviati.", "Завершено. Надіслано {} кадрів.";
SesPeerIs: "„{}” to {}.", "“{}” is {}.", "„{}“ ist {}.", "«{}» es {}.", "« {} » est {}.", "«{}» è {}.", "«{}» — це {}.";
SesFound: "Znalazłem „{}” pod {}.", "Found “{}” at {}.", "„{}“ unter {} gefunden.", "Encontrado «{}» en {}.", "« {} » trouvé à {}.", "Trovato «{}» a {}.", "Знайшов «{}» за {}.";
SesSeveral: "W sieci jest kilka odbiorników:", "There are several receivers on the network:", "Es gibt mehrere Empfänger im Netz:", "Hay varios receptores en la red:", "Il y a plusieurs récepteurs sur le réseau :", "Ci sono più ricevitori in rete:", "У мережі кілька приймачів:";
SesSkipping: "  pomijam „{}” — protokół w wersji {}, ja mówię {}", "  skipping “{}” — protocol version {}, I speak {}", "  überspringe „{}“ — Protokollversion {}, ich spreche {}", "  omito «{}» — protocolo versión {}, yo hablo {}", "  j’ignore « {} » — protocole version {}, je parle {}", "  salto «{}» — protocollo versione {}, io parlo {}", "  пропускаю «{}» — протокол версії {}, я говорю {}";
SesSearching: "Szukam odbiorników w sieci…", "Looking for receivers on the network…", "Suche Empfänger im Netz…", "Buscando receptores en la red…", "Recherche de récepteurs sur le réseau…", "Cerco ricevitori in rete…", "Шукаю приймачі в мережі…";
ErrCannotBind: "nie mogę zająć {}", "cannot take {}", "kann {} nicht belegen", "no puedo ocupar {}", "impossible d’occuper {}", "non riesco a occupare {}", "не можу зайняти {}";
ErrNoReceiver: "nie widzę żadnego odbiornika w sieci.\nUruchom `micbridge recv` na drugiej maszynie. Jeśli już działa, router może blokować ruch multicast między klientami — wtedy podaj adres wprost: `--to 192.168.1.40`.", "I see no receiver on the network.\nRun `micbridge recv` on the other machine. If it is already running, the router may be blocking multicast between clients — then give the address directly: `--to 192.168.1.40`.", "Ich sehe keinen Empfänger im Netz.\nStarte `micbridge recv` auf der anderen Maschine. Läuft er bereits, blockiert der Router vielleicht Multicast zwischen Clients — dann die Adresse direkt angeben: `--to 192.168.1.40`.", "No veo ningún receptor en la red.\nEjecuta `micbridge recv` en la otra máquina. Si ya está en marcha, el router puede bloquear el multicast entre clientes; entonces indica la dirección directamente: `--to 192.168.1.40`.", "Je ne vois aucun récepteur sur le réseau.\nLancez `micbridge recv` sur l’autre machine. S’il tourne déjà, le routeur bloque peut-être le multicast entre clients — indiquez alors l’adresse directement : `--to 192.168.1.40`.", "Non vedo alcun ricevitore in rete.\nAvvia `micbridge recv` sull’altra macchina. Se è già attivo, il router potrebbe bloccare il multicast tra client: allora indica l’indirizzo direttamente: `--to 192.168.1.40`.", "Не бачу жодного приймача в мережі.\nЗапустіть `micbridge recv` на іншій машині. Якщо він уже працює, роутер може блокувати багатоадресний трафік між клієнтами — тоді вкажіть адресу прямо: `--to 192.168.1.40`.";
ErrPickOne: "wskaż jeden: --to „nazwa” albo --to adres", "pick one: --to “name” or --to address", "wähle einen aus: --to „name“ oder --to adresse", "elige uno: --to «nombre» o --to dirección", "choisissez-en un : --to « nom » ou --to adresse", "scegline uno: --to «nome» oppure --to indirizzo", "виберіть один: --to «назва» або --to адреса";

// --- spis urządzeń ----------------------------------------------------------
CliDefaultMark: "* = domyślne w systemie.  Silnik pracuje przy {} Hz — inne częstotliwości są przeliczane.", "* = system default.  The engine runs at {} Hz — other rates are converted.", "* = Systemstandard.  Die Engine läuft mit {} Hz — andere Raten werden umgerechnet.", "* = predeterminado del sistema.  El motor trabaja a {} Hz; otras frecuencias se convierten.", "* = par défaut du système.  Le moteur tourne à {} Hz — les autres fréquences sont converties.", "* = predefinito di sistema.  Il motore lavora a {} Hz; le altre frequenze vengono convertite.", "* = типовий у системі.  Рушій працює на {} Гц — інші частоти перераховуються.";
CliPointing: "Wskazywanie: --device „yeti” albo --device @3", "Pointing: --device “yeti” or --device @3", "Auswahl: --device „yeti“ oder --device @3", "Selección: --device «yeti» o --device @3", "Désignation : --device « yeti » ou --device @3", "Selezione: --device «yeti» oppure --device @3", "Вибір: --device «yeti» або --device @3";
CliSinkLinux: "Ujście: --sink auto tworzy własny mikrofon „{}” w PipeWire.", "Sink: --sink auto creates our own “{}” microphone in PipeWire.", "Senke: --sink auto erzeugt ein eigenes Mikrofon „{}“ in PipeWire.", "Sumidero: --sink auto crea un micrófono propio «{}» en PipeWire.", "Puits : --sink auto crée notre propre microphone « {} » dans PipeWire.", "Destinazione: --sink auto crea un microfono nostro «{}» in PipeWire.", "Стік: --sink auto створює власний мікрофон «{}» у PipeWire.";
CliSinkLinuxNote: "        Nie ma go na liście powyżej — powstaje dopiero po połączeniu.", "        It is not in the list above — it appears only once connected.", "        Es steht nicht in der Liste oben — es entsteht erst bei Verbindung.", "        No está en la lista de arriba: aparece solo tras conectar.", "        Il ne figure pas dans la liste ci-dessus — il n’apparaît qu’une fois connecté.", "        Non è nell’elenco sopra: compare solo dopo la connessione.", "        Його немає у списку вище — він з’являється лише після з’єднання.";
CliSinkWindows: "Ujście: --sink auto szuka wirtualnego kabla wśród wyjść;", "Sink: --sink auto looks for a virtual cable among the outputs;", "Senke: --sink auto sucht ein virtuelles Kabel unter den Ausgängen;", "Sumidero: --sink auto busca un cable virtual entre las salidas;", "Puits : --sink auto cherche un câble virtuel parmi les sorties ;", "Destinazione: --sink auto cerca un cavo virtuale tra le uscite;", "Стік: --sink auto шукає віртуальний кабель серед виходів;";
CliSinkWindowsNote: "        Windows nie pozwala programowi utworzyć własnego mikrofonu.", "        Windows does not let a program create a microphone of its own.", "        Windows erlaubt einem Programm kein eigenes Mikrofon.", "        Windows no permite que un programa cree su propio micrófono.", "        Windows n’autorise pas un programme à créer son propre microphone.", "        Windows non consente a un programma di creare un proprio microfono.", "        Windows не дозволяє програмі створити власний мікрофон.";
CliNoMic: "Bez mikrofonu: --device {} nadaje sinus 440 Hz — sprawdza całą ścieżkę.", "Without a microphone: --device {} sends a 440 Hz sine — it exercises the whole path.", "Ohne Mikrofon: --device {} sendet einen 440-Hz-Sinus — prüft den ganzen Weg.", "Sin micrófono: --device {} envía un seno de 440 Hz y comprueba todo el recorrido.", "Sans microphone : --device {} émet un sinus 440 Hz — teste tout le trajet.", "Senza microfono: --device {} invia un seno a 440 Hz e verifica l’intero percorso.", "Без мікрофона: --device {} передає синус 440 Гц — перевіряє весь шлях.";
LanguageLabel: "Język:", "Language:", "Sprache:", "Idioma:", "Langue :", "Lingua:", "Мова:";
LangAutomatic: "automatycznie", "automatic", "automatisch", "automático", "automatique", "automatico", "автоматично";
}
